#**Scalar 0D Tensor**

In [ ]:
import tensorflow as tf
scalar = tf.constant(5)
print(scalar)

tf.Tensor(5, shape=(), dtype=int32)


#**Vector 1D Tensor**

A vector is a one dimensional tensor like an array. Example[1,2,3]

In [ ]:
import tensorflow as tf
vector = tf.constant([5,10,15,20])
print(vector)

tf.Tensor([ 5 10 15 20], shape=(4,), dtype=int32)


#**Matrix 2D Tensor**

A matrix is a 2 dimensional tensor(rows and columns)


In [ ]:
import tensorflow as tf
matrix = tf.constant([[1,2,3],[4,5,6]])
print(matrix)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


#**3D Tensor**

A 3D tensor is like a collection if matrices stacked together

In [ ]:
tensor_3d = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
print(tensor_3d)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


#**Higher Dimensional Tensors**

Used in deep learning for images vidoes and complex models.
Example of a 4D tensor:
Used for image processing with shape(batch_size,height,width,channels)

In [ ]:
tensor_4d  =tf.constant([[[[1],[2],[3],[4]]],[[[5],[6],[7],[8]]]])
print(tensor_4d)

tf.Tensor(
[[[[1]
   [2]
   [3]
   [4]]]


 [[[5]
   [6]
   [7]
   [8]]]], shape=(2, 1, 4, 1), dtype=int32)


#**Tensor Functions**

#tf.constant()
Create a constant tensor

In [ ]:
import tensorflow as tf
tensor = tf.constant([[1,2],[3,4]])
print(tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


#tf.zeros()

Create a tensor filled with zeros

In [ ]:
import tensorflow as tf
zero_tensor = tf.zeros([2,3])
print(zero_tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


#tf.ones()
Create a tensor filled with ones

In [ ]:
import tensorflow as tf
one_tensor = tf.ones([2,3])
print(one_tensor)


tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


#tf.random.uniform()
Create a tensor with random values

In [ ]:
import tensorflow as tf
random_tensor = tf.random.uniform([2,2],minval=0,maxval=10,dtype=tf.int32)
print(random_tensor)

tf.Tensor(
[[4 3]
 [0 6]], shape=(2, 2), dtype=int32)


#tf.shape()

Returns the shape of a tensor

In [ ]:
import tensorflow as tf
tensor = tf.constant([[1,2],[3,4]])
print(tf.shape( tensor))


tf.Tensor([2 2], shape=(2,), dtype=int32)


#Mathematical Operation

1.  tf.add() - Element-wise addition
2.  tf.subtract() - Element-wise subtraction
3. tf.multiply() - Element-wise multiplication
4. tf.divide() - Element-wise division
5. tf.matmul() - Matrix multiplication












In [ ]:
import tensorflow as tensor
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])
add = tf.add(a, b)
sub = tf.subtract(a, b)
mul = tf.multiply(a, b)
div = tf.divide(a, b)

print('Add',add)
print('Sub',sub)
print('Mul',mul)
print('Div',div)


Add tf.Tensor([5 7 9], shape=(3,), dtype=int32)
Sub tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
Mul tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
Div tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [ ]:
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])
result = tf.matmul(matrix1, matrix2)
print(result)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


### **Reshaping & Manipulating Tensors**
1.   tf.reshape() - Changes tensor shap
2.   tf.transpose() - Transposes a matrix
3.  tf.squeeze() - Removes dimensions of size 1
4.  tf.expand_dims() - Adds a new dimension



In [ ]:
import tensorflow as tf
tensor = tf.constant([1, 2, 3, 4, 5, 6])
reshaped_tensor = tf.reshape(tensor, [2, 3])
print(reshaped_tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
import tensorflow as tf
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])
transposed = tf.transpose(matrix)
print(transposed)

tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


In [ ]:
import tensorflow as tf
tensor = tf.constant([[[1], [2], [3]]])
squeezed = tf.squeeze(tensor)
print(squeezed)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [ ]:
import tensorflow as tf
tensor = tf.constant([1, 2, 3])
expanded = tf.expand_dims(tensor, axis=1)
print(expanded)


tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)


### **Aggregation Functions (Summarizing Data)**

1. tf.reduce_sum() - Computes sum of all elements
2. tf.reduce_mean() - Computes mean (average)
3. tf.reduce_max() & tf.reduce_min() - Finds max/min




In [ ]:
import tensorflow as tf
tensor = tf.constant([[1, 2,],[3, 4]])
sum = tf.reduce_sum(tensor)
print(sum)

tf.Tensor(10, shape=(), dtype=int32)


In [ ]:
mean_result = tf.reduce_mean(tensor)
print(mean_result)

tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
mean_result = tf.reduce_min(tensor)
print(mean_result)

tf.Tensor(1, shape=(), dtype=int32)


### **Indexing & Slicing Tensors**

In [ ]:
import tensorflow as tf
tensor = tf.constant([1, 2, 3, 4, 5])
print(tensor[0])
print(tensor[-1])

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)


In [ ]:
import tensorflow as tf
tensor = tf.constant([10, 20, 30, 40, 50])
print(tensor[1:4])

tf.Tensor([20 30 40], shape=(3,), dtype=int32)


### **Broadcasting in Tensors**

In [ ]:
import tensorflow as tf
tensor1 = tf.constant([[1, 2, 3]])
tensor2 = tf.constant([[1], [2], [3]])

result = tensor1 + tensor2
print(result)


tf.Tensor(
[[2 3 4]
 [3 4 5]
 [4 5 6]], shape=(3, 3), dtype=int32)
